/*
Highly divisible triangular number
Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ProjectEProbs._1to50;
using ProjectETests.Utilities;
using System.Numerics;

namespace ProjectETests.Probs1to50
{
    [TestFixture]
    [Category("Prob 12 Tests")]
    public class Prob12Tests
    {
        [Test]
        public void TestTriangleGen()
        {
            long[] correct = { 1, 3, 6, 10, 15, 21, 28, 36 };
            long[] generated = Prob12.TriangleNumberGenerator(1000).Take(8).ToArray();
            for (int i = 0; i < correct.Length;i++)
            {
                Assert.AreEqual(correct[i], generated[i]);
            }

        }

        [Test]
        public void TestTriangleNumWith5Div()
        {
            BigInteger solution = Prob12.Solve(5);
            Assert.AreEqual(28, solution);
        }

        [Test]
        public void TestTriangleNumWith500Div()
        {
            BigInteger solution = Prob12.Solve(500);
            TestUtils.WriteOut($"First triangle number with at least 500 divisors is {solution}.");
            Assert.AreEqual(28, solution);
        }
    }
}
